# -*- coding: utf-8 -*-
"""customer_deployment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QmBCv32ZHlTM0euQndBRVyu6F0KLqAOv
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans

st.title("Customer Segmentation App")

# Upload file
uploaded_file = st.file_uploader("Upload CSV file", type=["csv"])

if uploaded_file:
    data = pd.read_csv(uploaded_file)

    st.subheader("Dataset Preview")
    st.write(data.head())

    # Select features
    x = data[["Annual Income (k$)", "Spending Score (1-100)"]]

    # Elbow method
    st.subheader("Elbow Method")

    wcss = []
    for i in range(1, 10):
        kmeans = KMeans(n_clusters=i, random_state=42)
        kmeans.fit(x)
        wcss.append(kmeans.inertia_)

    fig, ax = plt.subplots()
    ax.plot(range(1, 10), wcss)
    ax.set_xlabel("Number of Clusters")
    ax.set_ylabel("WCSS")
    st.pyplot(fig)

    # Choose clusters
    k = st.slider("Select number of clusters", 2, 10, 5)

    # Apply KMeans
    kmeans = KMeans(n_clusters=k, random_state=42)
    y_pred = kmeans.fit_predict(x)

    data["Cluster"] = y_pred

    st.subheader("Clustered Data")
    st.write(data.head())

    # Plot clusters
    fig2, ax2 = plt.subplots()
    scatter = ax2.scatter(
        x["Annual Income (k$)"],
        x["Spending Score (1-100)"],
        c=y_pred
    )

    ax2.scatter(
        kmeans.cluster_centers_[:, 0],
        kmeans.cluster_centers_[:, 1],
        s=200,
        c="black"
    )

    ax2.set_xlabel("Annual Income")
    ax2.set_ylabel("Spending Score")

    st.pyplot(fig2)