# -*- coding: utf-8 -*-
"""customer_segmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lN7Xgdh2YupCALD6-BFwSCIcJSe9K-tH
"""

# drive mount
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

filepath ="/content/drive/MyDrive/Machine learning with python/Mall_Customers.csv"

data =pd.read_csv(filepath)

"""**Basic EDA**"""

#check the head
data.head(5)

data.tail(5)

data.columns

data.shape

data.info()

data.describe()

# checking missing value
data.isnull().sum()

#check duplicate value
data.duplicated().sum()

data["CustomerID"].unique()

data["CustomerID"].value_counts()

data["Gender"].unique()

data["Gender"].value_counts()

data["Age"].unique()

data["Age"].value_counts()

data["Annual Income (k$)"].unique()

data["Annual Income (k$)"].value_counts()

data["Spending Score (1-100)"].unique()

data["Spending Score (1-100)"].value_counts()

#scaling the data
'''
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
data["Annual Income (k$)"] = sc.fit_transform(data[[Annual Income (K$)]])
'''

"""**Data Visulazation**"""

# for numeric columns
# histogram
import matplotlib.pyplot as plt
import seaborn as sns

sns.histplot(data['Annual Income (k$)'],color="red",bins=15,kde=True)
plt.title("Age Distribution")
plt.show()

"""**Count plot**"""

plt.figure(figsize=(3,5))
sns.countplot(data["Age"],color = "green")
plt.title("Gender Distribution")
plt.show()

sns.scatterplot(data=data,x="Annual Income (k$)",y="Spending Score (1-100)",color="orange")
plt.title("Annual Income (k$) vs Spending Score (1-100)")
plt.show()

"""**Box plot**"""

sns.boxplot(data['Annual Income (k$)'],color="purple")
plt.title("Age Distribution")
plt.show()

data.columns

x = data[["Annual Income (k$)","Spending Score (1-100)"]]

x.head()

"""**Model Selection**"""

from sklearn.cluster import KMeans

wcss = []

for n in range(1,10):
  kmeans= KMeans(n_clusters=n,random_state=42)
  kmeans.fit(x)
  wcss.append(kmeans.inertia_)

print(wcss)

plt.plot(range(1,10),wcss)
plt.xlabel("number of cluster")
plt.ylabel("wcss")
plt.show()

kmeans = KMeans(n_clusters=5,random_state=42)
y_means = kmeans.fit_predict(x)

plt.scatter(data=x,x="Annual Income (k$)",y="Spending Score (1-100)",c=y_means,cmap="rainbow")
plt.xlabel("Annual Income (k$)")
plt.ylabel("Spending Score (1-100)")
plt.show()

data["cluster"] = y_means

plt.scatter(data=x,x="Annual Income (k$)",y="Spending Score (1-100)",c=y_means,cmap="rainbow")
plt.scatter(kmeans.cluster_centers_[:,0],
            kmeans.cluster_centers_[:,1],
            s=100,c="black")
plt.show()

from sklearn.metrics import silhouette_score

kmeans_score=silhouette_score(x,y_means)
print(kmeans_score)

"""**DBSCAN**"""

from sklearn.cluster import DBSCAN

dbscan = DBSCAN(eps=9,min_samples=5)
db_cluster = dbscan.fit_predict(x)

db_score = silhouette_score(x,db_cluster)
print(db_score)

#removing noise
import numpy as np
mask = db_cluster != -1
score_mask = silhouette_score(x[mask],db_cluster[mask])
print(score_mask)

data["db-cluster"] = db_cluster

import seaborn as sns
sns.scatterplot(data=data,x="Annual Income (k$)",y="Spending Score (1-100)",hue="db-cluster",palette="rainbow")
plt.show()

"""**PCA**"""

data["Gender"]=data["Gender"].map({"Male":0,"Female":1})

data.info()

# data visulaization after this

data["CustomerID"].unique()

x = data.drop("CustomerID",axis =1)

from sklearn.decomposition import PCA

pca = PCA(n_components=2)
x_pca = pca.fit_transform(x)

x_pca.shape

pca_df = pd.DataFrame(x_pca,columns=["pca1","pca2"])

pca.explained_variance_ratio_

"""value should be above 70 of pca
note - total varience explained is 89% - which is good
ideal above 80
"""

from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=5,random_state=42)

cluster_pca = kmeans.fit_predict(x_pca)

from sklearn.metrics import silhouette_score
pca_score_kmeans = silhouette_score(x_pca,cluster_pca)
print(pca_score_kmeans)

# DBSCAN

from sklearn.cluster import DBSCAN
dbsacn = DBSCAN(eps=9,min_samples=5)
db_cluster_pca= dbscan.fit_predict(x_pca)

score_db_pca = silhouette_score(x_pca,db_cluster_pca)
print(score_db_pca)

